# Generated by Django 4.1.7 on 2023-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('Management', 'Management'), ('Sales', 'Sales'), ('Support', 'Support')], max_length=16),
        ),
    ]
